add web hook
elkavitaly/OneSchedule pull request #34
Opened 2021-09-03 16:28 UTC by VallarDark

2021-09-03 16:38 UTC, gitrepository100 submitted a review, later dismissed
Approved

2021-09-06 07:48 UTC, elkavitaly requested changes

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +    public class SetWebHookService : IHostedService
I am not sure that this class should be placed in Domain project. It is mostly related to presentation layer, how app will receive messages. So, I think it's better to move it to OneSchedule project

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +            var assembly = AppDomain.CurrentDomain.GetAssemblies()
What is the purpose of this code?

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +            var configuration = new ConfigurationBuilder()
Isn't there any way to pass configuration using DI?

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +            var webHookSettings = new WebHookSettings()
Try to use IOptions patters and inject these values into the constructor

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +                if (webHookSettings.IsUsed)
Use ternary operator here

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Settings/WebHookSettings.cs
> +        public bool IsUsed { get; set; }
I prefer to name it IsEnabled

2021-09-06 07:48 UTC, elkavitaly commented on OneSchedule.Domain/SetWebHookService.cs
> +                var bot = new TelegramBotClient(telegramSettings.ApiKey);
Also use DI here

2021-09-06 11:42 UTC, elkavitaly requested changes

2021-09-06 11:42 UTC, elkavitaly commented on OneSchedule/SetWebHookService.cs
> +            if (!string.IsNullOrEmpty(_webHookOptions.Value.Uri) && _bot!=null)
Format code

2021-09-06 11:42 UTC, elkavitaly commented on OneSchedule/SetWebHookService.cs
> +                if (_webHookOptions.Value.IsEnable)
Use ternary operator

2021-09-06 11:42 UTC, elkavitaly commented on OneSchedule.Settings/WebHookSettings.cs
> +        public bool IsEnable { get; set; }
rename to **IsEnabled**

2021-09-06 11:42 UTC, elkavitaly commented on OneSchedule/appsettings.json
> +    "IsUsed": true,
Update config values according to property name

2021-09-06 12:14 UTC, elkavitaly approved these changes

2021-09-06 12:14 UTC, elkavitaly commented on OneSchedule/SetWebHookService.cs
> +            _webHookOptions = webHookOptions;
It is usually better to have a field of settings class itself instead of IOptions<T>

2021-09-06 12:25 UTC, gitrepository100 approved these changes
Approved

2021-09-06 12:27 UTC, merged